### ISSUE TITLE
 java.lang.IllegalArgumentException: unexpected url: GAYWNB2QS44BYJLDASCDKIO4X6Z4B2WHTZQPADLQZURLRQVRVGNA7HM5

### ISSUE THREAD

**Issue by saikiran143** [kinfoundation/android-stellar-sdk#15]
Sample App Getting crashed!!! Getting Illegal Argument Exception.

04-18 19:54:59.255 13383-13383/org.stellar.android.sample E/AndroidRuntime: FATAL EXCEPTION: main
    Process: org.stellar.android.sample, PID: 13383
    java.lang.RuntimeException: Unable to start activity ComponentInfo{org.stellar.android.sample/org.stellar.android.sample.MainActivity}: java.lang.IllegalArgumentException: unexpected url: GAYWNB2QS44BYJLDASCDKIO4X6Z4B2WHTZQPADLQZURLRQVRVGNA7HM5
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2426)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2490)
        at android.app.ActivityThread.-wrap11(ActivityThread.java)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1354)
        at android.os.Handler.dispatchMessage(Handler.java:102)
        at android.os.Looper.loop(Looper.java:148)
        at android.app.ActivityThread.main(ActivityThread.java:5443)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:728)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:618)
     Caused by: java.lang.IllegalArgumentException: unexpected url: GAYWNB2QS44BYJLDASCDKIO4X6Z4B2WHTZQPADLQZURLRQVRVGNA7HM5
        at okhttp3.Request$Builder.url(Request.java:143)
        at org.stellar.sdk.requests.ResponseHandler.handleGetRequest(ResponseHandler.java:37)
        at org.stellar.sdk.requests.AccountsRequestBuilder.account(AccountsRequestBuilder.java:29)
        at org.stellar.android.sample.MainActivity.onCreate(MainActivity.java:25)
        at android.app.Activity.performCreate(Activity.java:6259)
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1130)
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2379)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2490) 
        at android.app.ActivityThread.-wrap11(ActivityThread.java) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1354) 
        at android.os.Handler.dispatchMessage(Handler.java:102) 
        at android.os.Looper.loop(Looper.java:148) 
        at android.app.ActivityThread.main(ActivityThread.java:5443) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:728) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:618)

**Comment by josueMavarez** [comment]
Have found anything about this issue? I'm getting the same error here.

**Comment by josueMavarez** [comment]
@saikiran143 make sure you're calling server.accounts().account(keyPair) instead of server.accounts().account(URI.create(keyPair.accountId)). That should do it.

**Comment by NanneStephan** [comment]
you would think that but then you get a android.os.NetworkOnMainThreadException.
this could help then https://stackoverflow.com/questions/14124739/android-os-networkonmainthreadexception-on-service-start-on-android .

**Comment by josueMavarez** [comment]
Yeah, just remember to do Network stuff off the MainThread. You could use AsyncTask or RxJava.

**Comment by NanneStephan** [comment]
yes, https://github.com/javichaques/android-stellar-sdk javichaques got it working, so that would be a good point to start, he fixed some other issues to.
